Add enemy info
poooi/poi-server pull request #41
Opened 2018-09-19 11:39 UTC by gakada

Includes enemy stats, equipment and stage1/stage2 aircraft counts for air power estimation.

Another possible extension for this schema is to use friendly air power calculated in the viewer, real air status and `$min` to record lower air power bounds for air statuses.

2018-09-21 04:13 UTC, KagamiChan commented
what is the purpose for stage1 and stage2 plane remaining and loss without fleet air power?
seems we could sum up these to have a plane total, otherwise existing records will hardly get updated

2018-09-21 21:00 UTC, gakada commented
stage1 count is total number of fighters and bombers in the enemy fleet (for api_kouku at least, LBAS can include recons as well), stage2 count is total number of bombers (after stage1 loss, stage1 loss include both fighters and bombers, but since stage1 loss is minimized and stage2 total is maximized in the limit it is just total number of bombers in the enemy fleet, also stage1 - stage2 is then total number of fighters). Extracting fighter/bomber counts for already known enemies it is possible to find fighter/bomber counts for unknown enemies, with equipment also known, it can be possible to estimate or to find exact air power for unknown enemies (as sum(floor(sqrt(slot) * aa)), with exact slot, or sometimes estimated, like setting 0 for non plane slots, or dividing between all bombers/fighters w.r.t. stage1/stage2 counts, or using numbers of some related enemy form, etc.).

Frequently new air power is estimated using this method (that is, not based on friendly air power tests), e.g., some [@Croshadow_](https://twitter.com/Croshadow_), [@syoukuretin](https://twitter.com/syoukuretin) tweets, https://nga.178.com/read.php?tid=13930924, https://nga.178.com/read.php?tid=13930924&pid=295296601 for current event.

2018-09-24 04:23 UTC, gakada commented
As an example https://twitter.com/Croshadow_/status/1041280167832776704

![dnneyegvsae66jz](https://user-images.githubusercontent.com/13043588/45937451-08322280-bffb-11e8-968b-f0a5e7b1ebf4.jpg)

Here is stats, equipment, stage1 api_e_count = 168, api_e_lostcount = 0, stage2 api_e_count = 110 (in general api_e_lostcount != 0 case can still be useful, maybe having all possible configurations is even more useful, but I used `$min`/`$max` to have less records to `update`), or extracting known slots of 1579, 168 - 96 = 72 total, 168 - 110 - 32 = 26 fighters, 72 - 26 = 46 bombers for unknown 1776, assuming even distribution (46 / 2) it is [26, 23, 23] for slots, using equipment stats, floor(sqrt(26) * 10) + floor(sqrt(23) * 8) + floor(sqrt(23) * 8) = 126 air power (111 in extreme distribution case like floor(sqrt(26) * 10) + floor(sqrt(1) * 8) + floor(sqrt(45) * 8)). Without knowing api_e_lostcount and stage2 api_e_count still can estimate 126 as floor(sqrt(24) * 10) + floor(sqrt(24) * 8) + floor(sqrt(24) * 8) (72 / 3) just from stage1 api_e_count. For enemies with one plane slot this can be more exact, but the point is stage1 loss and stage2 count can be useful.

2018-09-29 06:30 UTC, KagamiChan commented
Thanks for the explanation, and sorry for being retarded. I think I somehow catch your idea.

one thing to confirm:
according to [the documentation](https://docs.mongodb.com/manual/reference/operator/update/), `$min` and `$max` only updates after comparing incoming value and existing value, is there any chance that a minimal `planeLost` and a maximal `planes2` that does not come from the same battle (say, Record 1 updates `planeLost` and Record2 updates `planes2`)

By the way, would you like to detail the model description in a similar way as current documentation in wiki page?

2018-09-29 10:31 UTC, gakada commented
Yeah, it can come from different battles, if stage 1 count is `f + b`, transitioning to stage 2 `(f - df) + (b - db)` with `df + db` loss and `b - db` count, then rather than storing values for individual battles, `$min` and `$max` are finding independent minimum and maximum for `df + db` and `b - db` for a given configuration `f + b`, most interesting case with loss = 0 will have the most information, always from the same battle.

Though based on this I think maybe it is more interesting to store `$max` stage 2 count (`b - db`) and `$min` stage 2 count + loss (`b + df`) instead. Loss = 0 case will have them equal (from the same battle), otherwise it is giving range `b - db <= b <= b + df` for bombers (from different battles).

Will do for wiki page. There is also some existing models that should be added.

2018-09-29 10:50 UTC, gakada commented
Changed schema to planes/bombersMin/bombersMax.

2018-11-26 06:50 UTC, KagamiChan requested changes
Sorry for keeping you waiting. I chose to put off this PR because of the fall event, and failed mind myself about it. All looks good except the commented lines

2018-11-26 06:50 UTC, KagamiChan commented on controllers/api/v2/report.es
> +      // bombersMax,
please remove comments here

2018-11-29 02:43 UTC, gakada commented on controllers/api/v2/report.es
> +      // bombersMax,
done :ok_hand:

2018-11-29 02:58 UTC, KagamiChan commented
LGTM cc @KochiyaOcean

2018-11-29 05:14 UTC, KagamiChan commented
cc @yukixz

2018-12-07 04:01 UTC, merged

2018-12-29 06:43 UTC, gakada commented
@KagamiChan I forgot to ask, is there a dump available for this collection?

2018-12-29 11:27 UTC, KagamiChan commented
@gakada I've added a cron task to dump the data, I'll inform you once it's ready

2019-01-02 02:28 UTC, KagamiChan commented
Sorry for being late

It will be available in 8 hours at https://poi.0u0.moe/dump/enemy-info.json

Currently you might also find the data named `enemy-stat.json`, it was my mistake

2019-01-05 18:16 UTC, gakada commented
Thanks.

By the way, both `enemy-info.json` and `ship-stat.json` are not real JSON files, but newline separated lists of JSON objects, maybe it can be wrapped in a JSON array for easier use? If in bash, something like

```sh
to_json () {
  printf [ > $1.json
  tr '\n' ',' < $1 | head -c -1 >> $1.json
  printf ] >> $1.json
  # rm $1
}

# ship-stat and enemy-info as they are now
to_json ship-stat
to_json enemy-info
```

So that `require`/`readJson` can be used at once, instead of writing `readFile`/`split`/`map`/`JSON.parse`/etc.

2019-01-09 12:40 UTC, KagamiChan commented
It's true they're not valid json files, however it might be better to convert them at user side.

With such format, a processor does not have to load the whole file into memory, instead the data could be loaded and processed by lines. This is meaningful for importing into another mongo database, and also for scripts running on low end machines, if someone likes to